# Generated by Django 5.0.6 on 2025-04-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('types', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('prix', models.IntegerField()),
                ('images', models.ImageField(upload_to='static/images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
