# Generated by Django 5.0.6 on 2025-04-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('pseudo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.TextField()),
                ('password', models.TextField()),
                ('photo', models.ImageField(upload_to='static/images/membres/')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
